### ISSUE TITLE
Vagrant up not finishing

### ISSUE THREAD

**Issue by docdentz** [emccode/mosaicme#4]
Hi,

just tried to vagrant up this app but it did not work unfortunately. He had issues doing the configurations with puppet. Any ideas on how to try and use the app?

br,

Daniel

**Comment by clintonskitson** [comment]
@pbutlerm Is this something that Magdy or Adrian can try and respond to?

**Comment by adrianmo** [comment]
Hi @docdentz, I will take a look at it and get back to you with whatever I find out :)

**Comment by adrianmo** [comment]
@docdentz sorry for the delay. I've been working on a deployment guide to make it easier for people to run MosaicMe.

https://github.com/emccode/mosaicme/blob/master/DEPLOYMENT.md

This guide is using the Docker images for MosaicMe as I think is the easiest way to get started with it. Though, I will try to fix the Vagrant environment whenever I find some time.

Hope it helps.

**Comment by docdentz** [comment]
Hi @adrianmo thx for the info. I'll try the guide. this will help me a lot.
